---
title: "NYC Restaurant Inspection Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r}

library(tidyverse)
library(ggplot2)
library(ggridges)
library(readxl)
library(dplyr)
library(janitor)
library(patchwork)
library(viridis)
library(plotly)
library(lubridate)
library(tidyr)
library(flexdashboard)
library(p8105.datasets)
data("rest_inspec")

set.seed(1)

# make dataset smaller and easier to work with 
rest_inspec =
  rest_inspec %>% 
  filter(action == "Violations were cited in the following area(s).") %>% 
  drop_na() %>% 
  select(-phone, -camis)
  
rest_inspec = mutate(rest_inspec, year = year(rest_inspec$inspection_date)) %>% 
  sample_n(5000)

```

Column {data-width=550}
-----------------------------------------------------------------------

### Number of Critical Violations By Borough

```{r}

# turn into a boxplot 

# axis labels 
x <- list(
  title = "Borough") 

y <- list(
  title = "Number of Critical Violations") 

# plot critical violations for each boro 
rest_inspec %>% 
  group_by(boro, critical_flag) %>% 
  summarize(n = n()) %>% 
  filter(critical_flag == "Critical") %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar") %>% 
  ungroup() %>% 
  layout(xaxis = x, yaxis = y)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Restaurant Inspection Grades By Borough

```{r}

# axis labels 
x <- list(
  title = "Borough") 

y <- list(
  title = "Number of Inspections") 

# number of A B C D E grades
rest_inspec %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  mutate(grade = as.factor(grade)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~grade,
          type = "bar",
          colors = "Set2") %>% 
  layout(xaxis = x, yaxis = y)

```

### Number of Critical Violations Over Time

```{r}

# axis labels 
x <- list(
  title = "Year") 

y <- list(
  title = "Number of Critical Violations") 

# plot number of critical violations over time
rest_inspec %>% 
  group_by(boro, critical_flag, year) %>% 
  summarize(n = n()) %>% 
  filter(critical_flag == "Critical") %>% 
  plot_ly(x = ~year, y = ~n, type = "scatter", mode = "line",
          alpha = 0.5,
          color = ~boro) %>% 
  ungroup() %>% 
  layout(xaxis = x, yaxis = y)

```

